import { DsaChallenge } from '../types';

export const DSA_CHALLENGES: DsaChallenge[] = [
  {
    id: 'dsa-fibonacci',
    title: 'Fibonacci Series (Dynamic Programming)',
    difficulty: 'Easy',
    category: 'Dynamic Programming',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    description: 'Compute the n-th Fibonacci number where each number is the sum of the two preceding ones.',
    solutions: {
      python: 'def fib(n: int) -> int: a, b = 0, 1; for _ in range(n): a, b = b, a + b; return a',
      javascript: 'function fibonacci(n) { let a = 0, b = 1; for (let i = 0; i < n; i++) [a, b] = [b, a + b]; return a; }',
      typescript: 'const fib = (n: number): number => { let a = 0, b = 1; for (let i = 0; i < n; i++) [a, b] = [b, a + b]; return a; };',
      cpp: 'int fib(int n) { int a = 0, b = 1; while (n--) { int temp = a + b; a = b; b = temp; } return a; }',
      java: 'public static int fib(int n) { int a = 0, b = 1; for (int i = 0; i < n; i++) { int temp = a + b; a = b; b = temp; } return a; }',
    },
  },
  {
    id: 'dsa-two-sum',
    title: 'Two Sum (Hash Map Lookup)',
    difficulty: 'Easy',
    category: 'Hash Map',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    description: 'Given an array of integers and a target, return indices of the two numbers such that they add up to target.',
    solutions: {
      python: 'def two_sum(nums, target): seen = {}; for i, num in enumerate(nums): diff = target - num; if diff in seen: return [seen[diff], i]; seen[num] = i',
      javascript: 'function twoSum(nums, target) { const map = new Map(); for (let i = 0; i < nums.length; i++) { const diff = target - nums[i]; if (map.has(diff)) return [map.get(diff), i]; map.set(nums[i], i); } }',
      typescript: 'function twoSum(nums: number[], target: number): number[] { const map = new Map<number, number>(); for (let i = 0; i < nums.length; i++) { const complement = target - nums[i]; if (map.has(complement)) return [map.get(complement)!, i]; map.set(nums[i], i); } return []; }',
      cpp: 'vector<int> twoSum(vector<int>& nums, int target) { unordered_map<int, int> m; for (int i = 0; i < nums.size(); i++) { int diff = target - nums[i]; if (m.count(diff)) return {m[diff], i}; m[nums[i]] = i; } return {}; }',
      java: 'public int[] twoSum(int[] nums, int target) { Map<Integer, Integer> map = new HashMap<>(); for (int i = 0; i < nums.length; i++) { int diff = target - nums[i]; if (map.containsKey(diff)) return new int[] {map.get(diff), i}; map.put(nums[i], i); } return new int[0]; }',
    },
  },
  {
    id: 'dsa-binary-search',
    title: 'Binary Search (Divide & Conquer)',
    difficulty: 'Easy',
    category: 'Binary Search',
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(1)',
    description: 'Search target in a sorted ascending array by repeatedly halving the search space.',
    solutions: {
      python: 'def binary_search(nums, target): low, high = 0, len(nums) - 1; while low <= high: mid = (low + high) // 2; if nums[mid] == target: return mid; elif nums[mid] < target: low = mid + 1; else: high = mid - 1; return -1',
      javascript: 'function binarySearch(arr, target) { let left = 0, right = arr.length - 1; while (left <= right) { const mid = Math.floor((left + right) / 2); if (arr[mid] === target) return mid; if (arr[mid] < target) left = mid + 1; else right = mid - 1; } return -1; }',
      typescript: 'function binarySearch(arr: number[], target: number): number { let l = 0, r = arr.length - 1; while (l <= r) { const mid = Math.floor((l + r) / 2); if (arr[mid] === target) return mid; arr[mid] < target ? l = mid + 1 : r = mid - 1; } return -1; }',
      cpp: 'int binarySearch(const vector<int>& v, int target) { int l = 0, r = v.size() - 1; while (l <= r) { int mid = l + (r - l) / 2; if (v[mid] == target) return mid; if (v[mid] < target) l = mid + 1; else r = mid - 1; } return -1; }',
      java: 'public int binarySearch(int[] nums, int target) { int l = 0, r = nums.length - 1; while (l <= r) { int mid = l + (r - l) / 2; if (nums[mid] == target) return mid; if (nums[mid] < target) l = mid + 1; else r = mid - 1; } return -1; }',
    },
  },
  {
    id: 'dsa-valid-palindrome',
    title: 'Valid Palindrome (Two Pointer)',
    difficulty: 'Easy',
    category: 'Two Pointers',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    description: 'Determine if a string reads identically forward and backward, ignoring non-alphanumeric characters.',
    solutions: {
      python: 'def is_palindrome(s: str) -> bool: filtered = [c.lower() for c in s if c.isalnum()]; return filtered == filtered[::-1]',
      javascript: 'function isPalindrome(s) { const clean = s.toLowerCase().replace(/[^a-z0-9]/g, ""); return clean === clean.split("").reverse().join(""); }',
      typescript: 'const isPalindrome = (s: string): boolean => { const clean = s.toLowerCase().replace(/[^a-z0-9]/g, ""); return clean === clean.split("").reverse().join(""); };',
      cpp: 'bool isPalindrome(string s) { int l = 0, r = s.size() - 1; while (l < r) { while (l < r && !isalnum(s[l])) l++; while (l < r && !isalnum(s[r])) r--; if (tolower(s[l++]) != tolower(s[r--])) return false; } return true; }',
      java: 'public boolean isPalindrome(String s) { int l = 0, r = s.length() - 1; while (l < r) { while (l < r && !Character.isLetterOrDigit(s.charAt(l))) l++; while (l < r && !Character.isLetterOrDigit(s.charAt(r))) r--; if (Character.toLowerCase(s.charAt(l++)) != Character.toLowerCase(s.charAt(r--))) return false; } return true; }',
    },
  },
  {
    id: 'dsa-reverse-linked-list',
    title: 'Reverse Linked List',
    difficulty: 'Medium',
    category: 'Linked List',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    description: 'Reverse a singly linked list in-place by updating next pointer references.',
    solutions: {
      python: 'def reverse_list(head): prev = None; curr = head; while curr: next_temp = curr.next; curr.next = prev; prev = curr; curr = next_temp; return prev',
      javascript: 'function reverseList(head) { let prev = null, curr = head; while (curr) { const next = curr.next; curr.next = prev; prev = curr; curr = next; } return prev; }',
      typescript: 'function reverseList<T>(head: ListNode<T> | null): ListNode<T> | null { let prev = null, curr = head; while (curr) { const n = curr.next; curr.next = prev; prev = curr; curr = n; } return prev; }',
      cpp: 'ListNode* reverseList(ListNode* head) { ListNode *prev = nullptr, *curr = head; while (curr) { ListNode* n = curr->next; curr->next = prev; prev = curr; curr = n; } return prev; }',
      java: 'public ListNode reverseList(ListNode head) { ListNode prev = null, curr = head; while (curr != null) { ListNode next = curr.next; curr.next = prev; prev = curr; curr = next; } return prev; }',
    },
  },
  {
    id: 'dsa-valid-parentheses',
    title: 'Valid Parentheses (Stack)',
    difficulty: 'Easy',
    category: 'Stack',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    description: 'Given a string containing parentheses, brackets, and braces, determine if the input sequence is valid and properly matched.',
    solutions: {
      python: 'def is_valid_parentheses(s: str) -> bool: stack = []; pairs = {")": "(", "}": "{", "]": "["}; for c in s: if c in pairs: if not stack or stack.pop() != pairs[c]: return False else: stack.append(c); return len(stack) == 0',
      javascript: 'function isValid(s) { const stack = [], pairs = { ")": "(", "}": "{", "]": "[" }; for (const c of s) { if (pairs[c]) { if (stack.pop() !== pairs[c]) return false; } else stack.push(c); } return stack.length === 0; }',
      typescript: 'function isValid(s: string): boolean { const stack: string[] = []; const map: Record<string, string> = {")": "(", "}": "{", "]": "["}; for (const char of s) { if (map[char]) { if (stack.pop() !== map[char]) return false; } else stack.push(char); } return stack.length === 0; }',
      cpp: 'bool isValid(string s) { stack<char> st; for (char c : s) { if (c == "(" || c == "{" || c == "[") st.push(c); else { if (st.empty()) return false; if (c == ")" && st.top() != "(") return false; if (c == "}" && st.top() != "{") return false; if (c == "]" && st.top() != "[") return false; st.pop(); } } return st.empty(); }',
      java: 'public boolean isValid(String s) { Stack<Character> stack = new Stack<>(); for (char c : s.toCharArray()) { if (c == "(") stack.push(")"); else if (c == "{") stack.push("}"); else if (c == "[") stack.push("]"); else if (stack.isEmpty() || stack.pop() != c) return false; } return stack.isEmpty(); }',
    },
  },
  {
    id: 'dsa-kadane',
    title: 'Kadane Algorithm (Maximum Subarray)',
    difficulty: 'Medium',
    category: 'Dynamic Programming',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    description: 'Find the contiguous subarray within a one-dimensional array of numbers which has the largest sum.',
    solutions: {
      python: 'def max_sub_array(nums): max_so_far = current_max = nums[0]; for x in nums[1:]: current_max = max(x, current_max + x); max_so_far = max(max_so_far, current_max); return max_so_far',
      javascript: 'function maxSubArray(nums) { let maxSoFar = nums[0], currentMax = nums[0]; for (let i = 1; i < nums.length; i++) { currentMax = Math.max(nums[i], currentMax + nums[i]); maxSoFar = Math.max(maxSoFar, currentMax); } return maxSoFar; }',
      typescript: 'function maxSubArray(nums: number[]): number { let current = nums[0], best = nums[0]; for (let i = 1; i < nums.length; i++) { current = Math.max(nums[i], current + nums[i]); best = Math.max(best, current); } return best; }',
      cpp: 'int maxSubArray(vector<int>& nums) { int cur = nums[0], res = nums[0]; for (size_t i = 1; i < nums.size(); ++i) { cur = max(nums[i], cur + nums[i]); res = max(res, cur); } return res; }',
      java: 'public int maxSubArray(int[] nums) { int cur = nums[0], best = nums[0]; for (int i = 1; i < nums.length; i++) { cur = Math.max(nums[i], cur + nums[i]); best = Math.max(best, cur); } return best; }',
    },
  },
];
