import { LearnItem } from '../types';

export const LEARN_CONCEPTS: LearnItem[] = [
  // --- Machine Learning & AI ---
  {
    id: 'ml-overfitting',
    term: 'Overfitting',
    category: 'machine_learning',
    categoryLabel: 'Machine Learning',
    definition: 'Overfitting occurs when a statistical model memorizes noise and detail in the training dataset to the extent that it negatively impacts performance on unseen validation data. It happens when model complexity is excessively high relative to sample size.',
    takeaway: 'Mitigate with L1/L2 regularization, dropout, cross-validation, and pruning.',
    difficulty: 'Beginner',
  },
  {
    id: 'ml-backpropagation',
    term: 'Backpropagation',
    category: 'machine_learning',
    categoryLabel: 'Machine Learning',
    definition: 'Backpropagation is the fundamental algorithm used to train feedforward neural networks. It computes the gradient of the loss function with respect to each weight using the mathematical chain rule, propagating errors backwards through layers.',
    takeaway: 'Computes gradients layer-by-layer backwards using the calculus chain rule.',
    difficulty: 'Intermediate',
  },
  {
    id: 'ml-transformer',
    term: 'Transformer Architecture',
    category: 'machine_learning',
    categoryLabel: 'Machine Learning',
    definition: 'A transformer is a deep learning architecture that dispenses with recurrent connections entirely, relying instead on self-attention mechanisms to capture long-range dependencies and compute contextual representations in parallel.',
    takeaway: 'Powers modern LLMs like GPT and Gemini; processes sequences simultaneously.',
    difficulty: 'Advanced',
  },
  {
    id: 'ml-gradient-descent',
    term: 'Gradient Descent',
    category: 'machine_learning',
    categoryLabel: 'Machine Learning',
    definition: 'Gradient descent is an iterative first-order optimization algorithm for finding a local minimum of a differentiable function. It takes proportional steps in the direction of the negative gradient at the current parameter estimate.',
    takeaway: 'Step size is determined by the learning rate hyperparameter alpha.',
    difficulty: 'Beginner',
  },
  {
    id: 'ml-attention-mechanism',
    term: 'Self-Attention Mechanism',
    category: 'machine_learning',
    categoryLabel: 'Machine Learning',
    definition: 'Self-attention calculates dynamic attention weights between all token pairs in a sequence. It allows each word vector to incorporate context from every other position simultaneously through query, key, and value dot products.',
    takeaway: 'Formula: softmax(Q * K.T / sqrt(d_k)) * V',
    difficulty: 'Advanced',
  },
  {
    id: 'ml-vector-embeddings',
    term: 'Vector Embeddings',
    category: 'machine_learning',
    categoryLabel: 'Machine Learning',
    definition: 'Vector embeddings are dense numerical arrays representing semantic entities like words, images, or code in high-dimensional vector space, such that conceptually similar items reside close to one another based on cosine distance.',
    takeaway: 'Foundational for vector databases, semantic search, and RAG systems.',
    difficulty: 'Intermediate',
  },
  {
    id: 'ml-reinforcement-learning',
    term: 'Reinforcement Learning',
    category: 'machine_learning',
    categoryLabel: 'Machine Learning',
    definition: 'Reinforcement learning trains autonomous software agents to make sequential decisions by rewarding desirable actions and penalizing adverse behaviors within an interactive Markov decision process environment.',
    takeaway: 'Balances exploration of uncharted states with exploitation of known rewards.',
    difficulty: 'Intermediate',
  },

  // --- System Design & Distributed Systems ---
  {
    id: 'sd-cap-theorem',
    term: 'CAP Theorem',
    category: 'system_design',
    categoryLabel: 'System Design',
    definition: 'The CAP theorem states that any distributed data store can simultaneously guarantee at most two out of three guarantees: Consistency (all nodes see the exact same data simultaneously), Availability (every request receives a non-error response), and Partition tolerance.',
    takeaway: 'In real-world networks with partitions, systems choose CP or AP.',
    difficulty: 'Intermediate',
  },
  {
    id: 'sd-acid',
    term: 'ACID Transactions',
    category: 'system_design',
    categoryLabel: 'System Design',
    definition: 'ACID is an acronym describing the four essential properties that guarantee database transaction reliability: Atomicity (all or nothing), Consistency (preserves schema constraints), Isolation (concurrent operations do not interfere), and Durability (committed changes persist).',
    takeaway: 'Standard for relational databases like PostgreSQL and MySQL.',
    difficulty: 'Beginner',
  },
  {
    id: 'sd-cache-invalidation',
    term: 'Cache Invalidation',
    category: 'system_design',
    categoryLabel: 'System Design',
    definition: 'Cache invalidation is a technique where cached copies of data are declared obsolete, purged, or refreshed whenever primary persistent records change. Strategies include write-through, write-behind, and cache-aside patterns.',
    takeaway: 'One of the two hardest problems in computer science alongside naming things.',
    difficulty: 'Intermediate',
  },
  {
    id: 'sd-idempotency',
    term: 'Idempotency',
    category: 'system_design',
    categoryLabel: 'System Design',
    definition: 'An operation is idempotent if applying it multiple successive times produces the exact same end state and side effects as executing it a single time. In HTTP protocols, GET, PUT, and DELETE methods are designed to be idempotent.',
    takeaway: 'Essential for reliable payment processing and network retry mechanisms.',
    difficulty: 'Intermediate',
  },
  {
    id: 'sd-event-driven',
    term: 'Event-Driven Architecture',
    category: 'system_design',
    categoryLabel: 'System Design',
    definition: 'Event-driven architecture is a distributed software design pattern where decoupled producer services publish state notifications to a central event stream or message broker without needing awareness of downstream consumer subscribers.',
    takeaway: 'Enables asynchronous decoupling, horizontal scaling, and fault isolation.',
    difficulty: 'Advanced',
  },
  {
    id: 'sd-sharding',
    term: 'Database Sharding',
    category: 'system_design',
    categoryLabel: 'System Design',
    definition: 'Database sharding is a horizontal partitioning strategy that divides a massive relational database into distinct, smaller, faster individual server instances known as shards, partitioned by a deterministically hashed shard key.',
    takeaway: 'Scales databases past single-machine hardware and memory limits.',
    difficulty: 'Advanced',
  },

  // --- Computer Science Core & Web Tech ---
  {
    id: 'cs-event-loop',
    term: 'JavaScript Event Loop',
    category: 'cs_core',
    categoryLabel: 'CS Fundamentals',
    definition: 'The JavaScript event loop constantly monitors the call stack and message queue. When the call stack becomes empty, it pushes asynchronous tasks, microtasks, and timer callbacks onto the stack for execution without blocking the single thread.',
    takeaway: 'Microtasks like Promise.then run before macrotasks like setTimeout.',
    difficulty: 'Intermediate',
  },
  {
    id: 'cs-virtual-dom',
    term: 'Virtual DOM',
    category: 'web_dev',
    categoryLabel: 'Web Engineering',
    definition: 'The Virtual DOM is a lightweight in-memory representation of real browser DOM nodes. UI libraries compare snapshots through a diffing algorithm and compute minimal batched mutations needed to synchronize the actual browser view.',
    takeaway: 'Minimizes expensive layout recalculations and browser repaints.',
    difficulty: 'Beginner',
  },
  {
    id: 'cs-deadlock',
    term: 'Deadlock & Dining Philosophers',
    category: 'cs_core',
    categoryLabel: 'CS Fundamentals',
    definition: 'A deadlock is a concurrency condition where two or more competing threads or processes are blocked indefinitely because each is holding a locked resource while waiting to acquire another lock held by the other thread.',
    takeaway: 'Requires mutual exclusion, hold and wait, no preemption, and circular wait.',
    difficulty: 'Intermediate',
  },
  {
    id: 'web-rest-vs-graphql',
    term: 'REST vs GraphQL',
    category: 'web_dev',
    categoryLabel: 'Web Engineering',
    definition: 'REST is an architectural style utilizing standard HTTP verbs across explicit resource endpoints, whereas GraphQL is a query language exposing a single endpoint where clients declare the precise shape and nested relationships of data requested.',
    takeaway: 'GraphQL eliminates over-fetching and under-fetching at the cost of caching complexity.',
    difficulty: 'Beginner',
  },
  {
    id: 'cs-garbage-collection',
    term: 'Garbage Collection (Mark & Sweep)',
    category: 'cs_core',
    categoryLabel: 'CS Fundamentals',
    definition: 'Garbage collection is automated runtime memory management that reclaims heap memory occupied by objects that are no longer accessible from root references. Mark-and-sweep identifies reachable objects before deallocating the remainder.',
    takeaway: 'Eliminates manual pointer deallocation bugs and memory leaks.',
    difficulty: 'Intermediate',
  },
];
