export const COMMON_WORDS: string[] = [
  "the", "be", "of", "and", "a", "to", "in", "he", "have", "it", "that", "for", "they", "I",
  "with", "as", "not", "on", "she", "at", "by", "this", "we", "you", "do", "but", "his",
  "from", "they", "say", "her", "she", "or", "an", "will", "my", "one", "all", "would",
  "there", "their", "what", "so", "up", "out", "if", "about", "who", "get", "which", "go",
  "me", "when", "make", "can", "like", "time", "no", "just", "him", "know", "take", "people",
  "into", "year", "your", "good", "some", "could", "them", "see", "other", "than", "then",
  "now", "look", "only", "come", "its", "over", "think", "also", "back", "after", "use",
  "two", "how", "our", "work", "first", "well", "way", "even", "new", "want", "because",
  "any", "these", "give", "day", "most", "us", "flow", "fast", "type", "code", "react",
  "speed", "clean", "logic", "focus", "light", "state", "build", "world", "great", "mind",
  "stream", "rapid", "power", "create", "system", "input", "result", "future", "simple",
  "design", "engine", "learn", "quick", "pulse", "drive", "skill", "space", "point",
  "screen", "change", "write", "number", "always", "water", "sound", "still", "small",
  "large", "found", "never", "thought", "under", "story", "while", "along", "might",
  "next", "hard", "open", "example", "begin", "life", "always", "those", "both", "paper",
  "together", "got", "group", "often", "run", "important", "until", "children", "side",
  "feet", "car", "mile", "night", "walk", "white", "sea", "began", "grow", "took",
  "river", "four", "carry", "state", "once", "book", "hear", "stop", "without", "second",
  "late", "miss", "idea", "enough", "eat", "face", "watch", "far", "really", "almost",
  "let", "above", "girl", "sometimes", "mountain", "cut", "young", "talk", "soon", "list",
  "song", "being", "leave", "family", "direct", "pose", "leave", "song", "measure", "door",
  "product", "black", "short", "numeral", "class", "wind", "question", "happen", "complete",
  "ship", "area", "half", "rock", "order", "fire", "south", "problem", "piece", "told",
  "knew", "pass", "since", "top", "whole", "king", "street", "inch", "multiply", "nothing",
  "course", "stay", "wheel", "full", "force", "blue", "object", "decide", "surface", "deep",
  "moon", "island", "foot", "system", "busy", "test", "record", "boat", "common", "gold",
  "possible", "plane", "stead", "dry", "wonder", "laugh", "thousand", "ago", "ran", "check",
  "game", "shape", "equate", "hot", "miss", "brought", "heat", "snow", "tire", "bring",
  "yes", "distant", "fill", "east", "paint", "language", "among", "unit", "power", "town",
  "fine", "certain", "fly", "fall", "lead", "cry", "dark", "machine", "note", "wait",
  "plan", "figure", "star", "box", "noun", "field", "rest", "correct", "able", "pound",
  "done", "beauty", "drive", "stood", "contain", "front", "teach", "week", "final", "gave",
  "green", "quick", "develop", "ocean", "warm", "free", "minute", "strong", "special", "mind"
];

export const PUNCTUATION_MARKS = [".", ",", "!", "?", ";", ":", "-", "\"", "'", "(", ")"];
